### ISSUE TITLE
 crawler["comment"] lock 처리하기

### ISSUE THREAD

**Issue by snoopspy** [bobbf/beaconflood#15]
서로 다른 스레드에서  crawler["comment"] 객체를 접근하고 있음. lock을 걸어 주지 않으면 프로그램이 크래시가 날 수도 있음. 확인 요망.

https://github.com/bobbf/beaconflood/commit/90706502338937cbb42b37e8ce523d5d982fb3ac

**Comment by SonMinWoo** [comment]
파이썬은 자체적으로 GIL이라는 메모리 보호기법을 사용해 CRASH를 방지합니다.
멀티프로세싱은 os에서 process들을 스케쥴하고 관리해줍니다.

**Comment by SonMinWoo** [comment]
@snoopspy list에 새로운 element를 추가시 락을 걸고 풀어주는 과정을 추가했습니다.
